version: '3'

services:
  web:
    build: .
    command: gunicorn -w 4 -b 0.0.0.0:8000 --timeout 600 app:app
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - celery_worker

  celery_worker:
    build: .
    command: celery -A app.celery worker --loglevel=info
