version: '3.8'

services:
  redis:
    image: redis:latest
    ports:
      - "6379:6379"

  web:
    build: .
    command: gunicorn -w 4 -b 0.0.0.0:8000 --timeout 600 app:app
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - redis
    environment:
      CELERY_BROKER_URL: redis://redis:6379/0
      CELERY_RESULT_BACKEND: redis://redis:6379/0
