version: '3.8'

services:
  web:
    build: .
    command: gunicorn -w 4 -b 0.0.0.0:8000 app:app
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - REDIS_HOST=svc.sel4.cloudtype.app
      - REDIS_PORT=30309
